### ISSUE TITLE
Pubsub emulator memory leak >= @google-cloud/pubsub 3.0.0

### ISSUE THREAD

**Issue by jhai420** [ert78gb/google-pubsub-emulator#106]
Hi - Has anyone experienced the issue of the emulator running out of memory after the upgrade to @google-cloud/pubsub 3.0.0? We use the pubsub emulator to run our integration tests with a docker image set up:

```
Build-agent version 1.0.167651-d52a9c2e (2023-04-18T11:21:26+0000)
System information:
 Server Version: 20.10.18
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.15.0-1030-aws
 Operating System: Ubuntu 20.04.5 LTS
 OSType: linux
 Architecture: x86_64

Starting container hiveops/circleci-deploy:16.14
```

Our resources run out almost immediately originally when setting up the emulator but even after we doubled our resources it runs out of memory during publishing:

![Screen Shot 2023-03-06 at 5 05 41 PM](https://user-images.githubusercontent.com/18757446/232942756-537c5ba9-0677-4c1e-9c05-1eb05d7e9cea.png)

**Comment by ert78gb** [comment]
My experience is to use 1 instance of `google-cloud/pubsub` per google project.
Technically the memory leak is in the `google-cloud/pubsub` package.
I haven't used this package for a while because I also use docker image setup and the container starts very slowly. So I use docker compose to start the container, delete and create the topics and subscriptions in the before/beforeEach section.

I decreased our test time drastically with this setup even if the test run serial instead of parallel.

I think I could optimise this library to use 1 `google-cloud/pubsub` instance per project, but I don't know your full setup so maybe it would not help you at the end of the day.

**Comment by jhai420** [comment]
> 

Hey! Sorry - I closed this issue without seeing your comment. It did turn out to be a `google-cloud/pubsub` issue that didn't like versions >= 3.0.0 and <= 3.3.0. Once we upgraded to 3.5.0, the memory leak was resolved!

**Comment by ert78gb** [comment]
Thx for the update
